name: Remove old artifacts

on:
  workflow_dispatch:
  # schedule:
  #   # Every Sunday at 1am
  #   - cron: '0 1 * * 0'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "1 week"
          # Optional inputs
          # skip-tags: true
          # skip-recent: 2
